line-length = 88
target-version = "py310"

[lint]
select = ["ALL"]

ignore = ["D203","D212","UP015"]

unfixable = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
