name: Python Unit Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0

      - name: Set PYTHONPATH
        run: |
          PWD=$(pwd)
          echo "PYTHONPATH=$PWD/src:$PWD/tests:$PYTHONPATH" >> $GITHUB_ENV

      - name: Install SQLite3
        run: 
          sudo apt-get update && sudo apt-get install -y sqlite3

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create database
        run: |
          make all

      - name: Run unit tests
        run: |
          python -m unittest discover
